- name: Week 02 Assignment
  hosts: lab
  
  tasks:
  - name: Hostname
    ansible.builtin.debug:
      var: ansible_facts['hostname']

  - name: IP Addresses
    ansible.builtin.debug:
      var: ansible_facts['all_ipv4_addresses']

  - name: Distribution Family
    ansible.builtin.debug:
      var: ansible_facts['distribution_file_variety']

  - name: Disk Size
    ansible.builtin.debug:
      var: ansible_facts['devices']['sda']['size']

  - name: RAM Size
    ansible.builtin.debug:
      var: ansible_facts['memtotal_mb']

  - name: Processor Core Count
    ansible.builtin.debug:
      var: ansible_facts['processor_cores']
